trigger:
  branches:
    include: [ '*' ]
    exclude: [ 'refs/tags/*' ]

pool:
  vmImage: windows-latest

steps:
- task: PowerShell@2
  displayName: Build
  inputs:
    filePath: .\build.ps1

- task: NuGetCommand@2
  displayName: Publish to MyGet
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'main'))
  inputs:
    command: push
    packagesToPush: 'artifacts\Packages\*.nupkg'
    nuGetFeedType: external
    publishFeedCredentials: MyGet

- task: PublishPipelineArtifact@1
  displayName: Publish package artifacts
  inputs:
    targetPath: artifacts\Packages
    artifact: Packages
    publishLocation: pipeline

- task: PublishPipelineArtifact@1
  displayName: Publish log artifacts
  inputs:
    targetPath: artifacts\Logs
    artifact: Logs
    publishLocation: pipeline
